name: Publish Package to GitHub Packages

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (leave empty to use package.json version)'
        required: false

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@osmova'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test || echo "No tests configured"
        continue-on-error: true

      - name: Build package
        run: yarn build

      - name: Configure npm authentication
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "@osmova:registry=https://npm.pkg.github.com" >> ~/.npmrc

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Summary
        run: |
          echo "## 📦 Package Published Successfully! 🎉" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Package**: @osmova/js-utils" >> $GITHUB_STEP_SUMMARY
          echo "**Version**: $(node -p "require('./package.json').version")" >> $GITHUB_STEP_SUMMARY
          echo "**Registry**: GitHub Packages" >> $GITHUB_STEP_SUMMARY
